//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int Employee_id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int JobTitle_id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual JobTitle JobTitle { get; set; }
    }
}
